"""Thin wrapper around spotipy calls used by the app."""


def get_candidate_tracks(sp, pool="top_tracks", limit=100):
    """Returns a flat list of track dicts: id, uri, name, artist_ids, popularity."""
    tracks = []
    fetched = 0
    page_size = 50

    while fetched < limit:
        batch_limit = min(page_size, limit - fetched)
        if pool == "saved":
            resp = sp.current_user_saved_tracks(limit=batch_limit, offset=fetched)
            items = [item["track"] for item in resp["items"]]
        else:
            resp = sp.current_user_top_tracks(limit=batch_limit, offset=fetched, time_range="medium_term")
            items = resp["items"]

        if not items:
            break

        for t in items:
            if not t:
                continue
            tracks.append({
                "id": t["id"],
                "uri": t["uri"],
                "name": t["name"],
                "artist_names": ", ".join(a["name"] for a in t["artists"]),
                "artists": [{"id": a["id"], "name": a["name"]} for a in t["artists"]],
                "popularity": t.get("popularity", 0),
            })

        fetched += len(items)
        if len(items) < batch_limit:
            break

    return tracks


def create_mood_playlist(sp, name, track_uris):
    """Creates a playlist for the current user.

    Spotify removed POST /users/{user_id}/playlists for Development Mode
    apps in the February 2026 migration (403 Forbidden) in favor of
    POST /me/playlists, which spotipy exposes as current_user_playlist_create.
    """
    playlist = sp.current_user_playlist_create(name, public=False, description="Generated by mood-to-genre matcher")
    if track_uris:
        sp.playlist_add_items(playlist["id"], track_uris[:100])
    return playlist
